import { Annotation } from '@langchain/langgraph';

/**
 * Review result produced by the Reviewer agent.
 */
export interface ReviewResult {
  qualityScore: number;
  summary: string;
  issues: string[];
  suggestions: string[];
  approved: boolean;
}

/**
 * A single test case generated by the Tester agent.
 */
export interface TestCase {
  name: string;
  description: string;
  inputData: string;
  expectedOutput: string;
  testCode: string;
}

/**
 * Aggregated test run results.
 */
export interface TestRunResult {
  passed: number;
  failed: number;
  total: number;
  failures: string[];
}

/**
 * LangGraph.js state annotation for the agent orchestration graph.
 *
 * Each field uses the default "last write wins" channel — when a node returns
 * a partial state update, LangGraph merges it by overwriting matching keys.
 * This mirrors the Python TypedDict(total=False) behaviour.
 */
export const AgentStateAnnotation = Annotation.Root({
  // Identity
  runId: Annotation<string>({ reducer: (_, b) => b, default: () => '' }),
  traceId: Annotation<string>({ reducer: (_, b) => b, default: () => '' }),

  // Input
  requirements: Annotation<string>({ reducer: (_, b) => b, default: () => '' }),

  // Agent outputs
  plan: Annotation<string | null>({ reducer: (_, b) => b, default: () => null }),
  code: Annotation<string | null>({ reducer: (_, b) => b, default: () => null }),
  review: Annotation<ReviewResult | null>({ reducer: (_, b) => b, default: () => null }),
  tests: Annotation<TestCase[]>({ reducer: (_, b) => b, default: () => [] }),
  testResults: Annotation<TestRunResult | null>({ reducer: (_, b) => b, default: () => null }),

  // Control flow
  currentAgent: Annotation<string>({ reducer: (_, b) => b, default: () => '' }),
  revisionCount: Annotation<number>({ reducer: (_, b) => b, default: () => 0 }),
  qualityScore: Annotation<number | null>({ reducer: (_, b) => b, default: () => null }),
  status: Annotation<'pending' | 'running' | 'completed' | 'failed'>({
    reducer: (_, b) => b,
    default: () => 'pending',
  }),

  // Cost tracking
  tokenUsage: Annotation<Record<string, number>>({ reducer: (_, b) => b, default: () => ({}) }),
  totalCostUsd: Annotation<number>({ reducer: (_, b) => b, default: () => 0 }),

  // Errors
  errors: Annotation<string[]>({
    reducer: (a, b) => [...a, ...b],
    default: () => [],
  }),
  lastError: Annotation<string | null>({ reducer: (_, b) => b, default: () => null }),
});

/**
 * Inferred type for the agent graph state.
 */
export type AgentState = typeof AgentStateAnnotation.State;

/**
 * Create an initial state for a new run.
 */
export function createInitialState(runId: string, requirements: string): AgentState {
  return {
    runId,
    traceId: '',
    requirements,
    plan: null,
    code: null,
    review: null,
    tests: [],
    testResults: null,
    currentAgent: '',
    revisionCount: 0,
    qualityScore: null,
    status: 'pending',
    tokenUsage: {},
    totalCostUsd: 0,
    errors: [],
    lastError: null,
  };
}
